doc/watch.sh
The current comment says that the docs generation script (/docs/watch.sh) watch for changes to .tex files. It actually listen on changes to .md. Presumably the extension were changed to .md so Github will display the docs.
I'll admit that this is pedantry. Feel free to reject if you don't give a damn :-)
I came accross it while reading the docs and wondering why there were variables in them.
=> Change comment in docs compilation script

contracts/GaugeController.vy, contracts/VotingEscrow.vy, tests/unitary/GaugeController/test_gaugecontroller_admin.py, tests/unitary/VotingEscrow/test_votingescrow_admin.py
* Check that `future_admin` has been set prior to applying a change in ownership.
* Add test cases.
=> Fix: apply admin

contracts/Minter.vy
Move the `Minted` event into the internal minting function.  This ensures the event fires during all minting functions, and fixes a compilation issue.
=> fix: `Minted` event

.github/workflows/gas.yaml, .github/workflows/main.yaml, requirements.txt
The `gas` job in the CI takes upwards of an hour to run. This PR modifies the workflow so that this job only runs on new commits to `master`.
=> Separate workflow for gas test

contracts/LiquidityGauge.vy, contracts/LiquidityGaugeReward.vy, tests/unitary/LiquidityGaugeReward/test_claim_rewards.py, tests/unitary/LiquidityGaugeReward/test_claim_rewards_none.py
* adjust `claimable_tokens` to accept an address as an input argument, instead of using `msg.sender`
* remove default arg for `claimable_rewards`
* merge `claim_rewards` and `claim_rewards_for` using default args
* expand test cases
=> Updates to LiquidityGauge and LiquidityGaugeReward

.github/workflows/main.yaml, brownie-config.yaml, contracts/VestingEscrow.vy, contracts/VestingEscrowFactory.vy, tests/conftest.py, tests/integration/LiquidityGauge/test_deposits_withdrawals.py, tests/integration/LiquidityGaugeReward/test_rewards_total.py, tests/integration/VestingEscrow/test_claim_partial.py, tests/integration/VotingEscrow/test_deposit_withdraw_voting.py, tests/unitary/VestingEscrow/test_claim.py, tests/unitary/VestingEscrow/test_disable_and_claim.py, tests/unitary/VestingEscrow/test_fund.py, tests/unitary/VestingEscrow/test_getters.py, tests/unitary/VestingEscrowFactory/test_claim_simple.py, tests/unitary/VestingEscrowFactory/test_deploy_escrow.py
* Gas optimizations for `VestingEscrow.fund`
* Increase number of recipients to 100
* Add "funding admins" that can only be used to create new vestings, and are disabled via `disable_fund_admins`
* Separate transfer of tokens from creating vestings using `add_tokens`
* Adjust/fix logic around min vesting duration in `VestingEscrowSimple`
* Update test cases
=> Updates to VestingEscrow

contracts/ERC20CRV.vy, tests/integration/ERC20CRV/test_mint_integration.py, tests/integration/ERC20CRV/test_mintable_in_timeframe.py, tests/unitary/ERC20CRV/test_inflation_delay.py, tests/unitary/ERC20CRV/test_mint.py, tests/unitary/Minter/test_minter.py
Add a delay before inflation of `ERC20CRV` begins.
* The first mining epoch is now `-1` and the rate starts at `0`.
* The initial epoch is set to end one day after employment (modifiable via `INFLATION_DELAY` constant).
* When the epoch changes from `-1` to `0`, the rate is adjusted to `INITIAL_RATE` instead of the usual decay.
This approach lets us delay inflation long enough to deploy all the contracts, and also lets users stake immediately. I have updated the test cases to confirm that minting is still possible during this new `-1` period - however the reward is zero.
=> Delayed inflation

contracts/VestingEscrow.vy, contracts/VestingEscrowFactory.vy, tests/conftest.py
* only enable `VestingEscrow` funding admin accounts if they are not `0x0`
* set admin during deployment of `VestingEscrowFactory`
=> Vesting escrow updates

.github/workflows/main.yaml, tests/integration/LiquidityGaugeReward/test_borked_rewards.py
* Add a test case to verify that withdrawals are possible if `CurveRewards` is broken from a call to `notifyRewardAmount` without the corresponding token transfer.
* Split the CI integration job between stateful and not-stateful tests to reduce waits on tests passing.
=> Borked rewards test

.github/workflows/gas.yaml, .github/workflows/main.yaml, package.json, requirements.txt, tests/unitary/VestingEscrowFactory/test_admin_simple.py, tests/unitary/VestingEscrowFactory/test_deploy_escrow.py, tests/unitary/VestingEscrowFactory/test_disable_simple.py
In the CI...
* add `package.json` to standardize installation of ganache across workflows, bump version to `6.11.0`
* add `NODE_OPTIONS` to CI env vars
* add caching to gas workflow
* bump various actions to `v2`
In the tests, I've removed the revert reason targets in some of the `VestingEscrowSimple` tests.  There is a brownie bug here and the fix for it requires more bandwidth than I can give it right now, so this is a quicker solution to ensure tests pass.
All of this work solves blockers to updating `PoolProxy` for fee distribution, which will be in another PR soon:tm:
=> Ci updates

contracts/LiquidityGaugeWrapper.vy, tests/conftest.py, tests/unitary/LiquidityGaugeWrapper/test_approve.py, tests/unitary/LiquidityGaugeWrapper/test_checkpoint.py, tests/unitary/LiquidityGaugeWrapper/test_claim_tokens.py, tests/unitary/LiquidityGaugeWrapper/test_deposit_withdraw.py, tests/unitary/LiquidityGaugeWrapper/test_transfer.py, tests/unitary/LiquidityGaugeWrapper/test_transferFrom.py
Add a wrapper for `LiquidityGauge` that tokenizes deposits.
The logic is mostly taken from `LiquidityGaugeReward`, but in this case the reward token is CRV.  The contract interface is almost identical to existing gauges + ERC20, with one new method `claim_tokens`. When using this wrapper it is not possible to boost a deposit, as the wrapped gauge sees the wrapper as the depositor.  But, for some use cases (aave) this is acceptable.
Run the tests.  I've added some new test modules specific to this contract.
=> tokenized wrapper for LiquidityGauge

contracts/LiquidityGaugeRewardWrapper.vy, tests/conftest.py, tests/unitary/LiquidityGaugeRewardWrapper/test_approve.py, tests/unitary/LiquidityGaugeRewardWrapper/test_checkpoint.py, tests/unitary/LiquidityGaugeRewardWrapper/test_claim_tokens.py, tests/unitary/LiquidityGaugeRewardWrapper/test_deposit_withdraw.py, tests/unitary/LiquidityGaugeRewardWrapper/test_transfer.py, tests/unitary/LiquidityGaugeRewardWrapper/test_transferFrom.py
Add a wrapper for `LiquidityGaugeRewards` that tokenizes deposits.
The logic is mostly taken from `LiquidityGaugeReward`.  Both CRV and the reward token are handled as reward tokens within the wrapper.  The contract interface is almost identical to existing gauges + ERC20, with one new method `claim_tokens` that claims both CRV and the reward token.
As with #53, when using this wrapper it is not possible to boost a deposit.
Run the tests.  I've added some new test modules specific to this contract.
=> tokenized wrapper for LiquidityGaugeRewards

contracts/PoolProxy.vy, tests/unitary/PoolProxy/test_owner_admin.py, tests/unitary/PoolProxy/test_proxy_burn.py
* consolidate `PoolProxy` burner logic into a single function
* add `burn_many` and `withdraw_many` for aggregated admin fee claims / burning
* represent ether as `0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE` instead of using `0x00`
* add a payable `__default__` method to allow receiving ether as a fee
Run the tests.  I've updated / expanded test cases around burning and withdrawing.
=> Updates to `PoolProxy`

contracts/PoolProxy.vy
* add `accept_transfer_ownership` method
* allow permissioning for `donate_admin_fees` on a per-pool basis
* modify re-entrancy locks so that burners can call into `donate_admin_fees`
=> Poolproxy updates

scripts/claim_and_burn_fees.py
Add a script that calls to withdraw and burn fees, sending them into the fee distributor.
=> Fee claim and burn script

contracts/gauges/LiquidityGaugeRewardWrapper.vy, contracts/gauges/LiquidityGaugeV2.vy, contracts/gauges/LiquidityGaugeWrapper.vy
Add a `Transfer` event to the `deposit` and `withdraw` functions of the tokenized gauge contracts. Without this, balances will not properly show in etherscan :scream:
=> Add `Transfer` event for gauge deposits and withdrawals

contracts/gauges/LiquidityGaugeV2.vy, tests/unitary/LiquidityGaugeV2/test_set_rewards.py
When calling `set_rewards`, validate that the claim signature works correctly.
=> Add claim check in `set_rewards`

contracts/gauges/LiquidityGaugeV2.vy
Use `raw_call` to handle transfer of reward tokens in `LiquidityGaugeV2`. This is useful in case we deal with a non-standard reward token.
=> LiquidityGaugeV2: use raw_call for reward token transfers

contracts/burners/ETHBurner.vy, tests/conftest.py, tests/fork/Burners/test_eth_burner.py
* bump vyper version
* enable the fork test for ETH - it was previously skipped because eth swaps weren't possible while the pool was undeployed
=> Eth burner updates

contracts/gauges/LiquidityGaugeV2.vy, tests/conftest.py
Set the name and symbol of `LiquidityGaugeV2` deployments based on the name and symbol of the staked LP token.
Confirm that the CI is passing.
=> Updates to GaugeV2 constructor logic

contracts/GaugeProxy.vy, tests/conftest.py, tests/unitary/GaugeProxy/test_gauge_ownership.py, tests/unitary/GaugeProxy/test_gauge_proxy_set_admins.py, tests/unitary/GaugeProxy/test_set_killed_gauge_proxy.py, tests/unitary/GaugeProxy/test_set_rewards_gauge_proxy.py
Build a proxy contract to allow the DAO to own `LiquidityGaugeV2` deployments.
=> Gauge ownership proxy

.pre-commit-config.yaml, README.md, requirements.txt, scripts/stats/gini.py, scripts/stats/plot_vecrv.py, scripts/stats/show_weekly_fees.py, tests/fork/conftest.py
Small PR for integrating [`brownie-token-tester`](https://github.com/iamdefinitelyahuman/brownie-token-tester) and remove redundant logic for custom ERC20 minting in tests. Also bumped versions for `isort` (removes `unknown_third_party` issues) and `flake`.
Integrating `brownie-token-tester` across Curve repos will take out a lot of duplicated logic, as well as make it easier to add and test custom ERC20 minting logic.
=> Integrate brownie-token-tester

contracts/gauges/LiquidityGaugeWrapperUnit.vy, contracts/testing/UnitVault.vy, scripts/stats/show_weekly_fees.py, tests/unitary/LiquidityGaugeWrapperUnit/conftest.py, tests/unitary/LiquidityGaugeWrapperUnit/test_approve.py, tests/unitary/LiquidityGaugeWrapperUnit/test_checkpoint.py, tests/unitary/LiquidityGaugeWrapperUnit/test_claim_tokens.py, tests/unitary/LiquidityGaugeWrapperUnit/test_deposit_withdraw.py, tests/unitary/LiquidityGaugeWrapperUnit/test_transfer.py, tests/unitary/LiquidityGaugeWrapperUnit/test_transferFrom.py, tests/unitary/LiquidityGaugeWrapperUnit/test_vault.py
Add a liquidity gauge wrapper that integrates with the unit.xyz [`Vault`](https://github.com/unitprotocol/core/blob/e5fb43009e23c39906a6366abc75c85ddd1b6ee5/contracts/Vault.sol) to allow users to claim CRV on their deposited collateral.
=> Gauge wrapper for Unit.xyz

contracts/gauges/RewardsOnlyGauge.vy, tests/conftest.py, tests/unitary/RewardsOnlyGauge/test_approve.py, tests/unitary/RewardsOnlyGauge/test_claim_historic_rewards.py, tests/unitary/RewardsOnlyGauge/test_claim_no_reward_contract.py, tests/unitary/RewardsOnlyGauge/test_claim_rewards_multiple.py, tests/unitary/RewardsOnlyGauge/test_claim_rewards_none.py, tests/unitary/RewardsOnlyGauge/test_claim_rewards_transfer.py, tests/unitary/RewardsOnlyGauge/test_claim_rewards_unipool.py, tests/unitary/RewardsOnlyGauge/test_deposit_for.py, tests/unitary/RewardsOnlyGauge/test_deposit_withdraw.py, tests/unitary/RewardsOnlyGauge/test_set_rewards.py, tests/unitary/RewardsOnlyGauge/test_set_rewards_deposit.py, tests/unitary/RewardsOnlyGauge/test_set_rewards_no_deposit.py, tests/unitary/RewardsOnlyGauge/test_transfer.py, tests/unitary/RewardsOnlyGauge/test_transferFrom.py
Modify `LiquidityGaugeV2` to create a gauge that issues __only__ third-party rewards.  This is useful for incentivizing pools on sidechains, where the gauge controller and CRV minter are unavailable.
Most of the added test cases were copied/adapted from tests for `LiquidityGaugeV2`.  I have added new tests around a unique behavior for this gauge - the ability to handle rewards that are directly transferred in, without requiring an explicit claim action.
=> Rewards-only gauge

tests/integration/RewardsOnlyGauge/test_rewards_total_transferred_in.py
Modified the existing `tests/integration/LiquidityGaugeReward/test_reward_total.py` stateful test, to work for the new RewardsOnlyGauge. Primarily verifies that rewards can be transferred directly into the gauge itself, instead of into a curve rewards contract for distribution.
Depends on: #96
=> Test Rewards Only Gauge Stateful

tests/unitary/Minter/test_minter.py
One of the minter tests was failing for one day of every week.  The issue is in the test, not the smart contract, and I've been ignoring it for months now - finally it became too annoying.
=> Fix flaky minter test

brownie-config.yaml, contracts/gauges/sidechain/CheckpointProxy.vy, contracts/gauges/sidechain/ChildChainStreamer.vy, contracts/gauges/sidechain/RootChainGauge.vy, contracts/gauges/sidechain/RootGaugeAnyswap.vy, contracts/gauges/sidechain/RootGaugePolygon.vy, contracts/gauges/sidechain/RootGaugeXdai.vy, tests/unitary/Sidechain/child_chain_streamer/test_add_reward.py, tests/unitary/Sidechain/child_chain_streamer/test_admin_functions.py, tests/unitary/Sidechain/child_chain_streamer/test_get_reward.py, tests/unitary/Sidechain/child_chain_streamer/test_notify_reward_amount.py, tests/unitary/Sidechain/child_chain_streamer/test_remove_reward.py, tests/unitary/Sidechain/conftest.py, tests/unitary/Sidechain/test_accept_transfer_ownership.py, tests/unitary/Sidechain/test_checkpoint_proxy.py, tests/unitary/Sidechain/test_commit_transfer_ownership.py, tests/unitary/Sidechain/test_root_checkpoint.py, tests/unitary/Sidechain/test_set_checkpoint_admin.py, tests/unitary/Sidechain/test_set_killed.py
Implementation of cross chain gauges to allow for the distribution of CRV rewards on side-chains via cross chain bridges, proxies and reward streamers.
Each side-chain will have an appropriate gauge on mainnet ethereum, and CRV will be minted to the root gauge, and then forwarded cross-bridge to the proper side-chain where rewards are streamed.
The root gauges have appropriate unit tests verifying their compatibility with the standard gauge API, as well as their ability to mint and forward their CRV to the appropriate addresses. All  external state changing functions have unit tests verifying functionality and proper behavior.
cc: @iamdefinitelyahuman
=> Cross Chain Gauges

brownie-config.yaml, contracts/gauges/sidechain/RootGaugeAnyswap.vy, contracts/gauges/sidechain/RootGaugePolygon.vy, contracts/gauges/sidechain/RootGaugeXdai.vy, tests/integration/ERC20CRV/test_mintable_in_timeframe.py, tests/unitary/Sidechain/conftest.py, tests/unitary/Sidechain/test_root_checkpoint.py, tests/unitary/Sidechain/test_sending_to_bridge.py
1. Fix issues in the emission schedule for `RootChain` gauges:
* The old logic was rolling the rate-change over until the start of the next epoch week, would could conflict with existing gauges and cause a revert due to exceeding `ERC20CRV.available_supply()`. In fixing I realized that we cannot rely on `ERC20CRV.rate` for the new rate because we are minting _ahead_ of schedule. The solution is to calculate the rate locally within the gauges, using the same maff as we use within `ERC20CRV`.
2. Increase test coverage.
* Tests for weekly emissions of each new gauge. One test compares the amount of CRV minted against a calculation in python, another compares mint amounts between `RootChainGauge` and `LiquidityGauge`. Given identical weights, the gauges should mint identical amounts.
* Tests …
=> RootChainGauge fixes and testing

contracts/gauges/LiquidityGaugeV3.vy
`_voting_escrow` has already been read previously and wouldn't change in between, we can reeuse it safely
=> Remove useless _voting_escrow read in kick

contracts/gauges/sidechain/RootGaugeHarmony.vy
This is a minimal modification from `RootGaugeXdai`, that approves and calls to the [Harmony ERC20 bridge](https://etherscan.io/address/0x2dccdb493827e15a5dc8f8b72147e6c4a5620857).
Use of the bridge requires the `CheckpointAdmin` (or manually pushing the transaction to the bridge, but lets not do that).
I have tested the bridge functionality here:
https://etherscan.io/address/0x360a2cd32a4a3f5b14b0c66dd42a0e5d2b89ec7f
https://explorer.harmony.one/address/0x360a2cd32a4a3f5b14b0c66dd42a0e5d2b89ec7f
=> Add root gauge for Harmony bridge

contracts/burners/eth/CryptoFactoryLPBurner.vy, tests/fork/Burners/test_crypto_factory_lp_burner.py
Factory Crypto LP Burner
- remove the most prioritised coin with 2% slippage according to price_oracle
- both coins are equally prioritised => remove both of them to save ratio
- revert if both coins have no priority
=> feat: add crypto factory lp burner

contracts/burners/eth/CryptoFactoryLPBurner.vy, contracts/burners/eth/CryptoLPBurner.vy, tests/fork/Burners/test_crypto_factory_lp_burner.py
Wrong indexes of coins were used to determine the type of crypto pool. Fixed that and added a comment in head of the contract.
Inverse price was used to calculate slippage. Added custom slippage.
=> fix: crypto burners
