curvefi/curve-dao-contracts

contracts/ERC20CRV.vy
contracts/GaugeController.vy
contracts/LiquidityGauge.vy
contracts/Minter.vy
contracts/PoolProxy.vy
contracts/VotingEscrow.vy
contracts/testing/CurvePool.vy
contracts/testing/ERC20.vy
contracts/testing/ERC20LP.vy
contracts/testing/Registry.vy
requirements.txt
tests/integration/GaugeController/test_vote_weight.py
tests/unitary/PoolProxy/test_emergency_admin.py
tests/unitary/PoolProxy/test_owner_admin.py
tests/unitary/PoolProxy/test_parameter_admin.py
tests/unitary/PoolProxy/test_proxy_burn.py

* Update syntax and test cases for vyper 0.2.0
* Reorder boolean operators to take advantage of short circuiting
* Return `True` from some contract calls to save gas re: `EXTCODEHASH`
* Handle `epoch` as `uint256` to save gas costs on clamping

Vyper 0.2.0 updates and optimizations

---

contracts/VotingEscrow.vy

For showing the deposit type in subgraph

VotingEscrow deposit event type

---

contracts/ERC20CRV.vy
contracts/GaugeController.vy
contracts/LiquidityGauge.vy
contracts/LiquidityGaugeReward.vy
contracts/Minter.vy
contracts/PoolProxy.vy
contracts/VestingEscrow.vy
contracts/VestingEscrowFactory.vy
contracts/VestingEscrowSimple.vy
contracts/VotingEscrow.vy
requirements.txt

Bump vyper version to [`v0.2.4`](https://github.com/vyperlang/vyper/releases/tag/v0.2.4).

Vyper 0.2.4

---

contracts/VestingEscrowFactory.vy
contracts/VestingEscrowSimple.vy
tests/conftest.py
tests/integration/LiquidityGaugeReward/test_rewards_total.py
tests/unitary/VestingEscrow/test_claim.py
tests/unitary/VestingEscrowFactory/test_claim_simple.py
tests/unitary/VestingEscrowFactory/test_deploy_escrow.py

* Alter `VestingEscrowFactory` so that the min vesting time is 1 year
* Update tests

Min vesting time

---

contracts/GaugeController.vy
contracts/VotingEscrow.vy

Use environment variables as default args in several functions in order to lower gas costs.

Environment vars as default values

---

contracts/LiquidityGauge.vy
contracts/LiquidityGaugeReward.vy
tests/unitary/LiquidityGauge/test_deposit_for.py
tests/unitary/LiquidityGaugeReward/test_deposit_for_rewards.py

Expand `LiquidityGauge.deposit` and `LiquidityGaugeReward.deposit` logic to allow deposits for other users, if approved.

Allow deposits for other users

---

tests/integration/ERC20CRV/test_mintable_in_timeframe.py
tests/integration/LiquidityGauge/test_deposits_withdrawals.py
tests/integration/LiquidityGaugeReward/test_rewards_ratio.py
tests/integration/LiquidityGaugeReward/test_rewards_total.py
tests/integration/Minter/test_components.py
tests/integration/VotingEscrow/test_deposit_withdraw_voting.py

* Fix a flaky test by decreasing the required precision from `1e-16` to `2e-16`
* Reduce the number of runs on some of the slower integration tests to speed up the CI

Test updates

---

scripts/deployment_config.py

Add vesting amounts for founder, investors, employees, etc.
This should be it - we're ready to go!

Vesting amounts

---

.github/workflows/main.yaml
README.md
contracts/README.md
contracts/testing/CurvePool.vy
contracts/testing/ERC20.vy
contracts/testing/ERC20LP.vy
requirements.txt

* update to use brownie `v1.11.0`
* cache compiler installations in CI
* add audits and other minor updates to `README.md`

Misc updates

---

contracts/PoolProxy.vy
contracts/testing/Registry.vy
contracts/testing/StableSwapSUSD.vy
tests/conftest.py
tests/unitary/PoolProxy/test_parameter_admin.py

The report: https://medium.com/@peter_4205/curve-vulnerability-report-a1d7630140ec
The fix limits the asymmetry of the pool at which the change can be applied. Asymmetry is defined as:
```
asymmetry = N * prod(balances) / sum(balances)
```
It is equal to 1 when pool is in ideal balance, and 0 if it's super-imbalanced. The acceptable asymmetry should be calculated when proposing the parameter change.

Fixing the issue with abrupt change of A

---

tests/conftest.py
tests/fork/conftest.py

* account alias fixtures
* `MintableTestToken` for minting tokens in fork mode

Updates to test fixtures

---

contracts/PoolProxy.vy

* only allow calling burn functions from an EOA
* add `burn_many`
* allow killing of burn functions

PoolProxy burn updates

---

contracts/FeeDistributor.vy
scripts/simulate_fee_distro.py
tests/conftest.py
tests/integration/FeeDistributor/test_checkpoint_ts.py
tests/integration/FeeDistributor/test_distribute_fees_stateful.py
tests/unitary/FeeDistribution/test_checkpoints.py
tests/unitary/FeeDistribution/test_claim_many.py
tests/unitary/FeeDistribution/test_fee_distribution.py
tests/unitary/FeeDistribution/test_kill.py

* Add `FeeDistributor` (#50)
* unit and integration tests for fee distribution
* forked simulation of actual distribution

Fee distribution 2

---

scripts/burners/claim_and_burn_fees.py

Bugfixes and verbosity improvements based on my most recent on of the claim script.

Updates to fee claim script

---

contracts/burners/ETHBurner.vy
contracts/burners/EuroBurner.vy
tests/fork/Burners/test_euro_burner.py

* Implement a burner contract for euro denominated stables.
* Add test cases.

Euro burner

---

scripts/burners/claim_and_burn_fees.py

Improvements to `claim_and_burn_fees` logic, specifically around synth burners.

Multiple synth burners

---

scripts/voting/new_vote.py

Update the voting script to also create and simulate emergency DAO votes.

Emergency DAO votes

---

scripts/burners/claim_and_burn_fees.py

Fix an issue in the fee claim script, where coins that have no price info on coin gecko were assumed to be worth $0

fix: coins where the rate is unavailable from coingecko

---

contracts/gauges/LiquidityGaugeV2.vy

* remove the warmup period prior to boosting rewards
* only transfer claimable rewards when the amount is non-zero

GaugeV2 updates

---

contracts/burners/ETHBurner.vy
tests/fork/Burners/test_eth_burner.py
tests/fork/Burners/test_lp_burner.py

This is a small PR which makes the following changes:
* add aETH (ankrETH) address to ETH burner 
* fix indentation error in burner tests

Add aETH to ETH burner

---

scripts/voting/new_vote.py

Handles pinning the vote description to IPFS within the voting script.

feat: pin to ipfs when making vote

---

scripts/voting/new_vote.py

Adds the ability to perform paramete votes using the `new_vote` script.

feat: parameter votes

---

scripts/voting/decode_vote.py
scripts/voting/new_vote.py

Minor updates to voting scripts.

Voting scripts

---

contracts/burners/CryptoLPBurner.vy

Added a burner to handle crypto pool LP tokens.  The logic is near-identical to the existing `LPBurner`.

LP burner for crypto pools

---

scripts/sidechain/checkpoint.py

Updates to the script for bridging CRV to various sidechains.

feat: sidechain checkpoint script

---

contracts/gauges/LiquidityGaugeV3.vy
contracts/gauges/RewardsOnlyGauge.vy

* Apply fixes in #105 to `RewardsOnlyGauge
* Standardize comments and formatting to reduce the diff between v3 and rewards-only

Standardize Gauges

---

scripts/sidechain/checkpoint.py

* Adds xDai gauges to the sidechain checkpointing script.
* Uses eip1559 `priority_fee`

feat: xdai sidechain emissions

---

contracts/gauges/sidechain/RootGaugeArbitrum.vy
contracts/streamers/RewardClaimer.vy
tests/fork/test_root_gauge.py

Root chain gauge for the Arbitrum bridge.

Arbitrum Gauge

---

scripts/sidechain/checkpoint.py

Simply call `brownie run sidechain/checkpoint get_checkpoint_delta`
Prints out the timedelta of `period_finish` - `now`, for timing when to call `notify_reward_amount` on sidechains.

feat: add checkpoint timedelta checker

---

contracts/gauges/LiquidityGaugeV4.vy

feat: liquidity gauge v4

---

scripts/voting/new_vote.py

Posting to Infura IPFS requires an account.

fix: new vote script

---

contracts/burners/eth/SwapCryptoBurner.vy
contracts/burners/eth/SwapStableBurner.vy
tests/fork/Burners/test_swap_crypto_burner.py
tests/fork/Burners/test_swap_stable_burner.py

`Swap2CryptoBurner` -> `SwapCryptoBurner`:
Support all CryptoPools for swaps with slippage protection
`SwapBurner` -> `SwapStableBurner`:
Support ETH implementations and remove crypto swaps

Swap burners update

---

contracts/burners/eth/crvUSDBurner.vy
tests/fork/Burners/test_crvburner.py

Burns LP tokens from Peg Keeper and crvUSD itself.
As for LPs it withdraws crvUSD for all pools but some prioritized.
Prioritized pools are maintained by the DAO and manager.
crvUSD is exchanged into the best available quantity from priority pools.

Add crvUSD burner

---

contracts/burners/eth/TricryptoFactoryLPBurner.vy
tests/fork/Burners/test_tricrypto_factory_lp_burner.py

Made in the design of Crypto Factory Burner.

Add tricrypto factory burner
